python: 2.7

matrix:
  env:
    - PACKAGE_VERSION="2.1.0"
  include:
  - os: linux
    dist: trusty
    compiler:
      - gcc
    language: python
    addons:
      sonarcloud:
        organization: "islog"
        token:
           secure: "cJ9Sg7kYCaHISdArKhNbpNjlpIIxVNRi6saoPqXmCW4msYIGoMuWazrYBOsH6z2E3lnAoqRzoCEHoXZJcOJTqK9gwH9L+CapMiqVy0PgGsyJp/oMUbbJlOJiF9BTRxnv5KhHHa2zRmI2ZVKq87/T5G4jmG23CqzBs3D4FkrrlNk="
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - g++-6
          - gcc-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      - PACKAGE_VERSION="2.1.0"
    script:
      - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-6
      - export CXX=/usr/bin/g++-6
      - wget "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip"
      - unzip sonar-scanner-cli-4.0.0.1744-linux.zip
      - export PATH=$PATH:/home/travis/build/islog/liblogicalaccess/sonar-scanner-cli-4.0.0.1744-linux.zip
      - mkdir build;
      - cd build
      - conan create .. LogicalAccess/$PACKAGE_VERSION@islog/$TRAVIS_BRANCH
      - conan install .. -o LLA_BUILD_UNITTEST=True --build gtest --build OpenSSL
      - build-wrapper-linux-x86-64 --out-dir . conan build ..
      - ctest
      - cd ..
      - sonar-scanner
    cache:
      directories:
        - '$HOME/.sonar/cache'

  - os: linux
    dist: trusty
    compiler:
      - clang
      - clang++
    language: python
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - libc++-dev
          - libc++abi-dev
          - libstdc++-6-dev
    env:
      - PACKAGE_VERSION="2.1.0"
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      - EXTRA_CXX_FLAGS="-stdlib=libstdc++-6-dev"
      - EXTRA_CXX_LINKER_FLAGS="-stdlib=libstdc++-6-dev"
      - EXTRA_LDFLAGS="-lstdc++"
    script:
      - export CC=/usr/bin/clang-6.0
      - export CXX=/usr/bin/clang++-6.0
      - mkdir build;
      - cd build
      - conan create .. LogicalAccess/$PACKAGE_VERSION@islog/$TRAVIS_BRANCH
      - conan install .. -o LLA_BUILD_UNITTEST=True --build gtest --build OpenSSL --build libstdc++-6-dev
      - conan build ..
      - ctest

before_install:
  - sudo apt-get install -y libpcsclite-dev
  - eval "${MATRIX_EVAL}"

install:
  - pip install conan
  - conan user
