python: 2.7

matrix:
  include:
  - os: linux
    dist: trusty
    compiler:
      - gcc
    language: python
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - g++-6
          - gcc-6
      coverity_scan:
        project:
          name: "islog/liblogicalaccess"
        build_command_prepend: "cov-configure --comptype gcc --compiler gcc-6 --template"
        build_command: "conan build .."
        notification_email: reports@islog.com
        branch_pattern: $TRAVIS_BRANCH

    before_install:
      - sudo apt-get install -y libpcsclite-dev
      - eval "${MATRIX_EVAL}"
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    install:
      - pip install conan
      - conan user
      - echo $PACKAGE_VERSION
      - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-6
      - export CXX=/usr/bin/g++-6
      - mkdir build;
      - cd build
      - conan install .. -o LLA_BUILD_UNITTEST=True
    script:
      - ctest
    env:
      - secure: "iCctxGh89wII03M6ni0tnvEnLJTaC6SCEJr95r/LBVZEMFu+zOYE3GoLO6CBGfIG38pLWAE6nAhxGfoq2oRspvxceUEph0xo8LhkuYu3uFgh+950oz6hPTwtKGznffng+xzhpQXwWbqx19wPddOvke1/iIJ1xlrfSIzi3S6wPuo="
      - PACKAGE_VERSION="2.1.0"
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-6"

  - os: linux
    dist: trusty
    compiler:
      - gcc
    language: python
    addons:
      sonarcloud:
        organization: "islog"
        token:
           secure: "cJ9Sg7kYCaHISdArKhNbpNjlpIIxVNRi6saoPqXmCW4msYIGoMuWazrYBOsH6z2E3lnAoqRzoCEHoXZJcOJTqK9gwH9L+CapMiqVy0PgGsyJp/oMUbbJlOJiF9BTRxnv5KhHHa2zRmI2ZVKq87/T5G4jmG23CqzBs3D4FkrrlNk="
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - g++-6
          - gcc-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      - PACKAGE_VERSION="2.1.0"
    before_install:
      - sudo apt-get install -y libpcsclite-dev
      - eval "${MATRIX_EVAL}"
    install:
      - pip install conan
      - conan user
    script:
      - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-6
      - export CXX=/usr/bin/g++-6
      - wget "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip"
      - unzip sonar-scanner-cli-4.0.0.1744-linux.zip
      - export PATH=$PATH:/home/travis/build/islog/liblogicalaccess/sonar-scanner-cli-4.0.0.1744-linux.zip
      - mkdir build;
      - cd build
      - conan install .. -o LLA_BUILD_UNITTEST=True
      - build-wrapper-linux-x86-64 --out-dir . conan build ..
      - ctest
      - cd ..
      - sonar-scanner
    cache:
      directories:
        - '$HOME/.sonar/cache'

  - os: linux
    dist: trusty
    compiler:
      - clang
      - clang++
    language: python
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - libc++-dev
          - libc++abi-dev
          - libstdc++-6-dev
    env:
      - PACKAGE_VERSION="2.1.0"
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      - EXTRA_CXX_FLAGS="-stdlib=libstdc++-6-dev"
      - EXTRA_CXX_LINKER_FLAGS="-stdlib=libstdc++-6-dev"
      - EXTRA_LDFLAGS="-lstdc++"
    before_install:
      - sudo apt-get install -y libpcsclite-dev
      - eval "${MATRIX_EVAL}"
    install:
      - pip install conan
      - conan user
    script:
      - export CC=/usr/bin/clang-6.0
      - export CXX=/usr/bin/clang++-6.0
      - mkdir build;
      - cd build
      - conan install .. -o LLA_BUILD_UNITTEST=True
      - conan build ..
      - ctest
