language: cpp
compiler: gcc
before_install: sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update -qq
install: sudo apt-get install -qq g++-4.7 gcc-4.8 libboost-dev libboost-system-dev libboost-filesystem-dev libboost-date-time-dev libpcsclite-dev libssl-dev
script: export CXX=gcc-4.7 && export CXX=g++-4.7 && cmake . && make && cd plugins/pluginscards/ && cmake . && make && cd ../pluginsreaderproviders/ && cmake . && make